# Generated by Django 5.1.4 on 2026-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='activitylog',
                    name='actor_name',
                    field=models.CharField(blank=True, help_text='Строковый снимок — история сохраняется даже если юзер удалён', max_length=80, verbose_name='имя исполнителя (snapshot)'),
                ),
                migrations.AlterField(
                    model_name='activitylog',
                    name='event_type',
                    field=models.CharField(choices=[('panel_move', 'Панель: перемещение'), ('panel_breakdown', 'Панель: поломка'), ('panel_condition_change', 'Панель: смена состояния'), ('panel_service', 'Панель: сервисные работы'), ('panel_comment', 'Панель: комментарий'), ('application_create', 'Заявка: создана'), ('application_transition', 'Заявка: смена статуса'), ('application_delete', 'Заявка: удалена'), ('application_executor_change', 'Заявка: смена исполнителя'), ('departure_create', 'Выезд: создан'), ('departure_complete', 'Выезд: выполнен'), ('departure_archive', 'Выезд: архивирован'), ('display_panel_replace', 'Экран: замена панели'), ('daily_task_complete', 'Задание: выполнено'), ('daily_task_reset', 'Задание: сброшено'), ('system', 'Системное')], max_length=40, verbose_name='тип события'),
                ),
                migrations.AlterField(
                    model_name='activitylog',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='activitylog',
                    name='payload',
                    field=models.JSONField(blank=True, default=dict, help_text='from_department, to_department, old_condition, etc.', verbose_name='доп. данные'),
                ),
            ],
        ),
    ]
