# Generated by Django 5.1.4 on 2026-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_alarms', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='alarmevent',
                    new_name='alarm_event_device__4328ff_idx',
                    old_name='alarm_event_device__7a3d9f_idx',
                ),
                migrations.RenameIndex(
                    model_name='alarmevent',
                    new_name='alarm_event_display_6bd70b_idx',
                    old_name='alarm_event_display_11e9ef_idx',
                ),
                migrations.AlterField(
                    model_name='alarmevent',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
