/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-0': 'var(--bg-0)',
        'bg-1': 'var(--bg-1)',
        'bg-2': 'var(--bg-2)',
        'bg-3': 'var(--bg-3)',
        'bg-4': 'var(--bg-4)',
        'fg-0': 'var(--fg-0)',
        'fg-1': 'var(--fg-1)',
        'fg-mute': 'var(--fg-mute)',
        'fg-faint': 'var(--fg-faint)',
        'accent-0': 'var(--accent-0)',
        'accent-1': 'var(--accent-1)',
        'accent-2': 'var(--accent-2)',
        'border-0': 'var(--border-0)',
        'border-1': 'var(--border-1)',
        danger: 'var(--danger)',
        warning: 'var(--warning)',
        success: 'var(--success)',
        info: 'var(--info)',
        fg: 'var(--fg)',
        'fg-dim': 'var(--fg-dim)',
        brand: 'var(--brand)',
        'brand-ink': 'var(--brand-ink)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-press': 'var(--accent-press)',
        'accent-faint': 'var(--accent-faint)',
        'accent-ink': 'var(--accent-ink)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border)',
        'border-strong': 'var(--border-strong)',
        ok: 'var(--ok)',
        'ok-faint': 'var(--ok-faint)',
        warn: 'var(--warn)',
        'warn-faint': 'var(--warn-faint)',
        err: 'var(--err)',
        'err-faint': 'var(--err-faint)',
        'info-faint': 'var(--info-faint)',
      },
      fontFamily: {
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '14px' }],
        xs: ['11px', { lineHeight: '16px' }],
        sm: ['12.5px', { lineHeight: '18px' }],
        base: ['13px', { lineHeight: '20px' }],
        md: ['14px', { lineHeight: '20px' }],
        lg: ['15px', { lineHeight: '22px' }],
        xl: ['17px', { lineHeight: '24px' }],
      },
      height: {
        row: 'var(--h-row)',
        'btn-sm': 'var(--h-btn-sm)',
        'btn-md': 'var(--h-btn-md)',
        'btn-lg': 'var(--h-btn-lg)',
        input: 'var(--h-input)',
        header: 'var(--h-header)',
        hit: 'var(--hit-target)',
      },
      minHeight: {
        hit: 'var(--hit-target)',
      },
      borderRadius: {
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
      },
      boxShadow: {
        popover: 'var(--shadow-popover)',
        modal: 'var(--shadow-modal)',
      },
      padding: {
        card: 'var(--pad-card)',
      },
    },
  },
  plugins: [],
}
