# Generated by Django 5.1.4 on 2025-08-05 07:44

import django.db.models.deletion
import zip.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=0, validators=[zip.models.validate_positive], verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Хаб',
                'verbose_name_plural': 'Хабы',
                'db_table': 'hubs_zip',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Lamels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=0, validators=[zip.models.validate_positive], verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Ламель',
                'verbose_name_plural': 'Ламели',
                'db_table': 'lamels_storage',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Имя')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=0, validators=[zip.models.validate_positive], verbose_name='Количество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Провод',
                'verbose_name_plural': 'Провода',
                'db_table': 'wires_zip',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='название"')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('status', models.CharField(choices=[('not_ready', 'Не готово'), ('ready', 'Доступно'), ('deadline', 'Дедлайн'), ('done', 'Выполнено'), ('undone', 'Не выполнено')], db_column='Статус', default='undone', max_length=20, verbose_name='Статус')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='начало')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='конец')),
                ('link', models.URLField(max_length=150, verbose_name='ссылка')),
                ('last_completed_date', models.DateField(blank=True, null=True, verbose_name='уведомление выполнение')),
                ('alert_notification_sent', models.BooleanField(default=False, verbose_name='уведомление скорое начало')),
                ('deadline_notification_sent', models.BooleanField(default=False, verbose_name='уведомление дедлайн')),
                ('lost_notification_sent', models.BooleanField(default=False, verbose_name='уведомление пропуск')),
                ('start_notification_sent', models.BooleanField(default=False, verbose_name='уведомление начало')),
                ('completed_notification_sent', models.BooleanField(default=False, verbose_name='уведомление выполнение')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cities', to_field='name', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'daily_task',
            },
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='экран')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('rows', models.PositiveIntegerField(default=0, verbose_name='кол-во рядов')),
                ('cols', models.PositiveIntegerField(default=0, verbose_name='кол-во столбцов')),
                ('camera_link', models.URLField(max_length=150, null=True, verbose_name='ссылка на камеру')),
                ('file', models.FileField(blank=True, default='file_not_found.jpg', null=True, upload_to='files/', verbose_name='Электросхема')),
                ('project_photo', models.FileField(blank=True, default='file_not_found.jpg', null=True, upload_to='files/', verbose_name='Проект')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='display', to='main.cities', to_field='name', verbose_name='город')),
            ],
            options={
                'verbose_name': 'Экран',
                'verbose_name_plural': 'Экраны',
                'db_table': 'display',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Panels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='айдишник')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('application_status', models.ForeignKey(default='default', null=True, on_delete=django.db.models.deletion.PROTECT, to='application.applicationstatus', to_field='name', verbose_name='статус заявки')),
                ('condition', models.ForeignKey(default='work', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.condition', to_field='name', verbose_name='состояние')),
                ('department', models.ForeignKey(default='zip', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.department', to_field='name', verbose_name='нахождение')),
                ('display', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zip.display', to_field='name', verbose_name='установлен на')),
            ],
            options={
                'verbose_name': 'Панель',
                'verbose_name_plural': 'Панели',
                'db_table': 'panel',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhotoDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/display_photos/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='zip.display', verbose_name='Экран')),
            ],
            options={
                'verbose_name': 'Фото экрана',
                'verbose_name_plural': 'Фото экрана',
                'db_table': 'photo_display',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(editable=False, verbose_name='ряд')),
                ('col', models.PositiveIntegerField(editable=False, verbose_name='столбец')),
                ('display', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cell_set', to='zip.display', to_field='name', verbose_name='экран')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell', to='zip.panels', to_field='name', verbose_name='панель')),
            ],
            options={
                'verbose_name': 'Ячейка',
                'verbose_name_plural': 'Ячейки',
                'db_table': 'cell',
                'ordering': ['display', 'row', 'col'],
                'constraints': [models.UniqueConstraint(fields=('panel',), name='unique_panel'), models.UniqueConstraint(fields=('display', 'row', 'col'), name='unique_display_row_col')],
            },
        ),
    ]
