# Generated by Django 5.1.4 on 2026-05-06 03:47

import apps.directory.storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_storage', '0001_initial_state_import'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='hubs',
                    options={'ordering': ['id'], 'verbose_name': 'Хаб', 'verbose_name_plural': 'Хабы'},
                ),
                migrations.AlterModelOptions(
                    name='lamels',
                    options={'ordering': ['id'], 'verbose_name': 'Ламель', 'verbose_name_plural': 'Ламели'},
                ),
                migrations.AlterModelOptions(
                    name='wires',
                    options={'ordering': ['id'], 'verbose_name': 'Провод', 'verbose_name_plural': 'Провода'},
                ),
                migrations.AlterField(
                    model_name='hubs',
                    name='count',
                    field=models.PositiveIntegerField(default=0, validators=[apps.directory.storage.models.validate_non_negative], verbose_name='Количество'),
                ),
                migrations.AlterField(
                    model_name='hubs',
                    name='description',
                    field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
                ),
                migrations.AlterField(
                    model_name='hubs',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='hubs',
                    name='name',
                    field=models.CharField(max_length=20, unique=True, verbose_name='Имя'),
                ),
                migrations.AlterField(
                    model_name='hubs',
                    name='photo',
                    field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
                ),
                migrations.AlterField(
                    model_name='lamels',
                    name='count',
                    field=models.PositiveIntegerField(default=0, validators=[apps.directory.storage.models.validate_non_negative], verbose_name='Количество'),
                ),
                migrations.AlterField(
                    model_name='lamels',
                    name='description',
                    field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
                ),
                migrations.AlterField(
                    model_name='lamels',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='lamels',
                    name='name',
                    field=models.CharField(max_length=20, unique=True, verbose_name='Имя'),
                ),
                migrations.AlterField(
                    model_name='lamels',
                    name='photo',
                    field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
                ),
                migrations.AlterField(
                    model_name='wires',
                    name='count',
                    field=models.PositiveIntegerField(default=0, validators=[apps.directory.storage.models.validate_non_negative], verbose_name='Количество'),
                ),
                migrations.AlterField(
                    model_name='wires',
                    name='description',
                    field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание'),
                ),
                migrations.AlterField(
                    model_name='wires',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='wires',
                    name='name',
                    field=models.CharField(max_length=20, unique=True, verbose_name='Имя'),
                ),
                migrations.AlterField(
                    model_name='wires',
                    name='photo',
                    field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
                ),
            ],
        ),
    ]
