# Generated by Django 5.1.4 on 2026-05-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_references', '0002_alter_cities_options_alter_color_options_and_more'),
        ('directory_displays', '0004_alter_cell_options_alter_display_options_and_more'),
        ('directory_panels', '0002_remove_panel_application_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='panel',
                    options={'ordering': ['id'], 'verbose_name': 'Панель', 'verbose_name_plural': 'Панели'},
                ),
                migrations.AlterField(
                    model_name='panel',
                    name='condition',
                    field=models.ForeignKey(default='work', null=True, on_delete=django.db.models.deletion.PROTECT, to='core_references.condition', verbose_name='состояние'),
                ),
                migrations.AlterField(
                    model_name='panel',
                    name='department',
                    field=models.ForeignKey(default='zip', null=True, on_delete=django.db.models.deletion.PROTECT, to='core_references.department', verbose_name='нахождение'),
                ),
                migrations.AlterField(
                    model_name='panel',
                    name='display',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory_displays.display', verbose_name='установлен на'),
                ),
                migrations.AlterField(
                    model_name='panel',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
