# Generated by Django 5.1.4 on 2025-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последней активности')),
                ('comment_monitoring', models.TextField(max_length=300, null=True, verbose_name='Коммент отправки заявки мониторинга')),
                ('time_monitoring', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки заявки мониторинга')),
                ('file_monitoring', models.FileField(blank=True, null=True, upload_to='application/', verbose_name='Фото отправки заявки мониторинг')),
                ('user_monitoring', models.CharField(blank=True, max_length=40, null=True, verbose_name='Работник')),
                ('comment_control_apply', models.TextField(max_length=300, null=True, verbose_name='Коммент принятия заявки контроль')),
                ('time_control_apply', models.DateTimeField(blank=True, null=True, verbose_name='Время принятие заявки контроль')),
                ('file_control_apply', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Фото контроль принятие заявки')),
                ('user_control_apply', models.CharField(blank=True, max_length=40, null=True, verbose_name='Работник')),
                ('comment_control_send', models.TextField(max_length=300, null=True, verbose_name='Коммент отправки заявки контроль')),
                ('time_control_send', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки заявки контроль')),
                ('file_control_send', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Фото контроль отправка заявки')),
                ('user_control_send', models.CharField(blank=True, max_length=40, null=True, verbose_name='Работник')),
                ('comment_service_apply', models.TextField(max_length=300, null=True, verbose_name='Коммент принятия заявки сервис')),
                ('time_service_apply', models.DateTimeField(blank=True, null=True, verbose_name='Время принятие заявки сервис')),
                ('file_service_apply', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Фото сервис принятие заявки')),
                ('user_service_apply', models.CharField(blank=True, max_length=40, null=True, verbose_name='Работник')),
                ('comment_control_at_work', models.TextField(max_length=300, null=True, verbose_name='Коммент проведенной работы по заявке в сервисе')),
                ('time_control_at_work', models.DateTimeField(blank=True, null=True, verbose_name='Время проведенной работы по заявке в сервисе')),
                ('file_control_at_work', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Фото проведенной работы по заявке в сервисе')),
                ('user_control_at_work', models.CharField(blank=True, max_length=40, null=True, verbose_name='Работник')),
                ('comment_control_unable', models.TextField(max_length=300, null=True, verbose_name='Коммент проведенной работы по заявке в сервисе')),
                ('time_control_unable', models.DateTimeField(blank=True, null=True, verbose_name='Время проведенной работы по заявке в сервисе')),
                ('file_control_unable', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Фото проведенной работы по заявке в сервисе')),
                ('user_control_unable', models.CharField(blank=True, max_length=40, null=True, verbose_name='Работник')),
                ('comment_control_archive', models.TextField(max_length=300, null=True, verbose_name='Коммент архивирования заявки в сервисе')),
                ('time_control_archive', models.DateTimeField(blank=True, null=True, verbose_name='Время архивирования заявки в сервисе')),
                ('file_control_archive', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Фото архивирования заявки в сервисе')),
                ('user_control_archive', models.CharField(blank=True, max_length=40, null=True, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявка',
                'db_table': 'application',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(max_length=5, null=True, verbose_name='Айди заявки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('comment', models.TextField(verbose_name='коммент')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('user', models.CharField(max_length=40, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История репортов заявок',
                'verbose_name_plural': 'Истории репортов заявок',
                'db_table': 'history_application',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, unique=True, verbose_name='название"')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'db_table': 'application_status',
                'ordering': ['id'],
            },
        ),
    ]
