# Generated by Django 5.1.4 on 2024-12-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_monitoring', models.TextField(max_length=300, null=True, verbose_name='Коммент мониторинга')),
                ('time_monitoring', models.DateTimeField(blank=True, null=True, verbose_name='Время мониторинга')),
                ('comment_control', models.TextField(max_length=300, null=True, verbose_name='Коммент контроля')),
                ('time_control', models.DateTimeField(blank=True, null=True, verbose_name='Время мониторинга')),
                ('comment_service', models.TextField(max_length=300, null=True, verbose_name='Комменты мониторинга')),
                ('time_service', models.DateTimeField(blank=True, null=True, verbose_name='Время мониторинга')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявка',
                'db_table': 'application',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('comment', models.TextField(verbose_name='коммент')),
                ('time', models.DateTimeField(verbose_name='время')),
                ('user', models.CharField(max_length=20, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'История репортов заявок',
                'verbose_name_plural': 'Истории репортов заявок',
                'db_table': 'history_application',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, unique=True, verbose_name='название"')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
                'db_table': 'application_status',
                'ordering': ['id'],
            },
        ),
    ]
