# Generated by Django 5.1.4 on 2025-08-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zip.cell', verbose_name='ячейка'),
        ),
        migrations.AddField(
            model_name='application',
            name='display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='zip.display', to_field='name', verbose_name='экран'),
        ),
    ]
