# Generated by Django 5.1.4 on 2024-12-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        ('main', '0001_initial'),
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zip.display', to_field='name', verbose_name='экран'),
        ),
        migrations.AddField(
            model_name='application',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zip.panels', to_field='name', verbose_name='панель'),
        ),
        migrations.AddField(
            model_name='applicationhistoryreport',
            name='display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zip.display', to_field='name', verbose_name='дисплей'),
        ),
        migrations.AddField(
            model_name='applicationhistoryreport',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='zip.panels', to_field='name', verbose_name='панель'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_status_color', to='main.color', to_field='name', verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='color_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_status_color_text', to='main.color', to_field='name', verbose_name='цвет текста'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.smile', to_field='smile_icon', verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application.applicationstatus', to_field='name', verbose_name='Статус'),
        ),
    ]
