# Generated by Django 5.1.4 on 2025-08-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0002_initial'),
        ('departure', '0001_initial'),
        ('main', '0001_initial'),
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departure.executor', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='application',
            name='panel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='zip.panels', to_field='name', verbose_name='панель'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_status_color', to='main.color', to_field='name', verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='color_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_status_color_text', to='main.color', to_field='name', verbose_name='цвет текста'),
        ),
        migrations.AddField(
            model_name='applicationstatus',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.smile', to_field='smile_icon', verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='application.applicationstatus', to_field='name', verbose_name='Статус'),
        ),
    ]
