# Generated by Django 5.1.4 on 2024-12-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('user_create', models.CharField(max_length=20, verbose_name='создатель')),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='время создания')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='время начала выезда')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='время окончания выезда')),
                ('result', models.TextField(blank=True, null=True, verbose_name='результат выезда')),
                ('contractor', models.TextField(blank=True, null=True, verbose_name='исполнитель')),
                ('notification', models.JSONField(blank=True, null=True, verbose_name='уведомления')),
                ('status', models.CharField(blank=True, default='created')),
            ],
            options={
                'verbose_name': 'Выезд',
                'verbose_name_plural': 'Выезды',
                'db_table': 'departure',
                'ordering': ['id'],
            },
        ),
    ]
