# Generated by Django 5.1.4 on 2025-05-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('user_create', models.CharField(max_length=20, verbose_name='Создатель')),
                ('time_updated', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего взаимодействия')),
                ('time_created', models.DateTimeField(blank=True, null=True, verbose_name='Время создания')),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Время начала выезда')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания выезда')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат выезда')),
                ('notification', models.JSONField(blank=True, null=True, verbose_name='Уведомления')),
                ('status', models.CharField(blank=True, default='Создан')),
            ],
            options={
                'verbose_name': 'Выезд',
                'verbose_name_plural': 'Выезды',
                'db_table': 'departure',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('executor_role', models.CharField(default='должности нет', max_length=20, verbose_name='Должность')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('telegram_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Айди телеграм')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'db_table': 'executor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='Описание')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона')),
                ('telegram_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Айди телеграм')),
                ('displays', models.ManyToManyField(related_name='contacts', to='zip.display', verbose_name='Список экранов')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contact',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DepartureHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('comment', models.TextField(verbose_name='Коммент')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('departure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departure.departure', verbose_name='Выезд')),
            ],
            options={
                'verbose_name': 'История репортов выездов',
                'verbose_name_plural': 'Истории репортов выездов',
                'db_table': 'departure_history_report',
                'ordering': ['id'],
            },
        ),
    ]
