# Generated by Django 5.1.4 on 2026-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_daily_tasks', '0001_initial_state_import'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='dailytask',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
