# Generated by Django 5.1.4 on 2026-05-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow_daily_tasks", "0002_alter_dailytask_id"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="dailytask",
                    name="notified_stages",
                    field=models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Отправленные уведомления",
                    ),
                ),
            ],
        ),
    ]
