# Generated by Django 5.1.4 on 2025-08-05 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='имя')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 'city',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Цвет')),
                ('hex_color', models.CharField(max_length=7, unique=True, verbose_name='Код цвета')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'db_table': 'color',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Smile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smile_icon', models.CharField(max_length=15, unique=True, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Иконка',
                'verbose_name_plural': 'Иконки',
                'db_table': 'smile',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='название отдела')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_color', to='main.color', to_field='name', verbose_name='цвет')),
                ('color_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_color_text', to='main.color', to_field='name', verbose_name='цвет текста')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.smile', to_field='smile_icon', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'department',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Состояние')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_color', to='main.color', to_field='name', verbose_name='цвет фона')),
                ('color_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_color_text', to='main.color', to_field='name', verbose_name='цвет текста')),
                ('icon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.smile', to_field='smile_icon', verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
                'db_table': 'condition',
                'ordering': ['id'],
            },
        ),
    ]
