# Generated by Django 5.1.4 on 2024-12-19 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='displays',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='zip.display', verbose_name='Экраны'),
        ),
        migrations.AddField(
            model_name='condition',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_color', to='main.color', to_field='name', verbose_name='цвет фона'),
        ),
        migrations.AddField(
            model_name='condition',
            name='color_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condition_color_text', to='main.color', to_field='name', verbose_name='цвет текста'),
        ),
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_color', to='main.color', to_field='name', verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='department',
            name='color_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_color_text', to='main.color', to_field='name', verbose_name='цвет текста'),
        ),
        migrations.AddField(
            model_name='panelstatus',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_status_color', to='main.color', to_field='name', verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='panelstatus',
            name='color_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='panel_status_color_text', to='main.color', to_field='name', verbose_name='цвет текста'),
        ),
        migrations.AddField(
            model_name='panelstatus',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.smile', to_field='smile_icon', verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.smile', to_field='smile_icon', verbose_name='иконка'),
        ),
        migrations.AddField(
            model_name='condition',
            name='icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.smile', to_field='smile_icon', verbose_name='иконка'),
        ),
    ]
