# Generated by Django 5.1.4 on 2026-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_references', '0001_initial_state_import'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='cities',
                    options={'ordering': ['id'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
                ),
                migrations.AlterModelOptions(
                    name='color',
                    options={'ordering': ['id'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
                ),
                migrations.AlterModelOptions(
                    name='condition',
                    options={'ordering': ['id'], 'verbose_name': 'Состояние', 'verbose_name_plural': 'Состояния'},
                ),
                migrations.AlterModelOptions(
                    name='department',
                    options={'ordering': ['id'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
                ),
                migrations.AlterModelOptions(
                    name='smile',
                    options={'ordering': ['id'], 'verbose_name': 'Иконка', 'verbose_name_plural': 'Иконки'},
                ),
                migrations.AlterField(
                    model_name='cities',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='color',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='condition',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='department',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='smile',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
