# Generated by Django 5.1.4 on 2026-05-06 03:47

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core_references', '0002_alter_cities_options_alter_color_options_and_more'),
        ('user', '0001_initial_state_import'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='msuser',
                    options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='allowed_city',
                    field=models.ManyToManyField(blank=True, to='core_references.cities', verbose_name='Разрешённые города'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='date_joined',
                    field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='groups',
                    field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='is_active',
                    field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='is_staff',
                    field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='is_superuser',
                    field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='max_id',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Айди MAX (VK мессенджер)'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='permission',
                    field=models.CharField(choices=[('monitoring', 'Мониторинг'), ('control', 'Контроль'), ('service', 'Сервис'), ('all', 'Все'), ('admin', 'Админ'), ('technical', 'Техник'), ('none_type', 'Никакие')], default='none_type', max_length=20, verbose_name='Уровень доступа'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='telegram_id',
                    field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Айди Telegram'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='user_permissions',
                    field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
                ),
                migrations.AlterField(
                    model_name='msuser',
                    name='username',
                    field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
                ),
            ],
        ),
    ]
