# Generated by Django 5.1.4 on 2026-05-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_role_and_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='msuser',
            name='show_activity_feed',
            field=models.BooleanField(default=False, help_text='T-8-020: включает блок «Последние действия» на главном экране для этого пользователя.', verbose_name='Показывать ленту действий на главной'),
        ),
    ]
