# Generated by Django 5.1.4 on 2025-05-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTaskHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='пользователь')),
                ('result', models.CharField(max_length=20, verbose_name='результат')),
                ('time', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reports', to='zip.dailytask', to_field='name', verbose_name='задание')),
            ],
            options={
                'verbose_name': 'История репортов задания',
                'verbose_name_plural': 'Истории репортов заданий',
                'db_table': 'history_daily',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DisplayHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коммент')),
                ('type_event', models.CharField(choices=[('moving', 'Передвижение'), ('breakdown', 'Поломка'), ('status', 'Статус'), ('service', 'Ремонт'), ('none_type', 'Общий')], default='none_type', max_length=20)),
                ('time', models.DateTimeField()),
                ('user', models.CharField(blank=True, max_length=20, null=True, verbose_name='пользователь')),
                ('display', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='display_history', to='zip.display', to_field='name', verbose_name='экран')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zip.cell', verbose_name='слот')),
            ],
            options={
                'verbose_name': 'История репортов экрана',
                'verbose_name_plural': 'Истории репортов экранов',
                'db_table': 'history_report',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PanelHistoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коммент')),
                ('type_report', models.CharField(choices=[('moving', 'Передвижение'), ('breakdown', 'Поломка'), ('condition', 'Состояние'), ('service', 'Ремонт'), ('none_type', 'Общий')], default='none_type', max_length=20)),
                ('time', models.DateTimeField()),
                ('user', models.CharField(blank=True, max_length=20, null=True, verbose_name='пользователь')),
                ('panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='zip.panels', to_field='name', verbose_name='панель')),
            ],
            options={
                'verbose_name': 'История репортов панелей',
                'verbose_name_plural': 'Истории репортов панелей',
                'db_table': 'history_panel',
                'ordering': ['id'],
            },
        ),
    ]
