# Generated by Django 5.1.4 on 2026-05-06 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_displays', '0004_alter_cell_options_alter_display_options_and_more'),
        ('directory_panels', '0003_alter_panel_options_alter_panel_condition_and_more'),
        ('workflow_applications', '0004_strip_application_prefix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='application',
                    options={'ordering': ['id'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
                ),
                migrations.AlterModelOptions(
                    name='applicationevent',
                    options={'ordering': ['occurred_at'], 'verbose_name': 'Событие заявки', 'verbose_name_plural': 'События заявок'},
                ),
                migrations.AlterModelOptions(
                    name='applicationhistoryreport',
                    options={'ordering': ['id'], 'verbose_name': 'История заявки (legacy)', 'verbose_name_plural': 'История заявок (legacy)'},
                ),
                migrations.AlterModelOptions(
                    name='applicationstatus',
                    options={'ordering': ['id'], 'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статусы заявок'},
                ),
                migrations.RemoveField(
                    model_name='application',
                    name='display_id',
                ),
                migrations.RemoveField(
                    model_name='application',
                    name='panel_id',
                ),
                migrations.AlterField(
                    model_name='application',
                    name='cell',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory_displays.cell', verbose_name='ячейка'),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='comment_control_apply',
                    field=models.TextField(max_length=300, null=True),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='comment_control_archive',
                    field=models.TextField(max_length=300, null=True),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='comment_control_at_work',
                    field=models.TextField(max_length=300, null=True),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='comment_control_send',
                    field=models.TextField(max_length=300, null=True),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='comment_control_unable',
                    field=models.TextField(max_length=300, null=True),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='comment_monitoring',
                    field=models.TextField(max_length=300, null=True, verbose_name='Коммент мониторинга'),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='comment_service_apply',
                    field=models.TextField(max_length=300, null=True),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='display',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='directory_displays.display', verbose_name='экран'),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='application',
                    name='panel',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='directory_panels.panel', verbose_name='панель'),
                ),
                migrations.AlterField(
                    model_name='applicationevent',
                    name='actor',
                    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_events', to=settings.AUTH_USER_MODEL, verbose_name='исполнитель'),
                ),
                migrations.AlterField(
                    model_name='applicationevent',
                    name='actor_name',
                    field=models.CharField(blank=True, help_text='Сохраняем как строку — если юзер удалён, история сохраняется', max_length=80, verbose_name='имя исполнителя (snapshot)'),
                ),
                migrations.AlterField(
                    model_name='applicationevent',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='applicationevent',
                    name='stage',
                    field=models.CharField(choices=[('monitoring_create', 'Создана мониторингом'), ('control_apply', 'Принята контролем'), ('control_send', 'Отправлена в сервис'), ('service_apply', 'Принята сервисом'), ('service_complete', 'Ремонт выполнен'), ('service_unable', 'Ремонт невозможен'), ('archive_done', 'Архивирована (выполнена)'), ('archive_unable', 'Архивирована (невозможно)')], max_length=30, verbose_name='этап'),
                ),
                migrations.AlterField(
                    model_name='applicationhistoryreport',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='applicationstatus',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
