# Generated by Django 5.1.4 on 2026-05-06 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_references', '0002_alter_cities_options_alter_color_options_and_more'),
        ('directory_displays', '0003_photo_display_state_import'),
        ('directory_panels', '0002_remove_panel_application_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='cell',
                    options={'ordering': ['display', 'row', 'col'], 'verbose_name': 'Ячейка', 'verbose_name_plural': 'Ячейки'},
                ),
                migrations.AlterModelOptions(
                    name='display',
                    options={'ordering': ['id'], 'verbose_name': 'Экран', 'verbose_name_plural': 'Экраны'},
                ),
                migrations.AlterField(
                    model_name='cell',
                    name='display',
                    field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cell_set', to='directory_displays.display', verbose_name='экран'),
                ),
                migrations.AlterField(
                    model_name='cell',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='cell',
                    name='panel',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell', to='directory_panels.panel', verbose_name='панель'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='camera_link',
                    field=models.URLField(max_length=150, null=True, verbose_name='ссылка на камеру'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='city',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='display', to='core_references.cities', verbose_name='город'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='cols',
                    field=models.PositiveIntegerField(default=0, verbose_name='кол-во столбцов'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='description',
                    field=models.TextField(blank=True, null=True, verbose_name='описание'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='file',
                    field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Электросхема'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='project_photo',
                    field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Проект'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='rows',
                    field=models.PositiveIntegerField(default=0, verbose_name='кол-во рядов'),
                ),
                migrations.AlterField(
                    model_name='display',
                    name='slug',
                    field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
                ),
                migrations.AlterField(
                    model_name='photodisplay',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AddConstraint(
                    model_name='cell',
                    constraint=models.UniqueConstraint(fields=('panel',), name='unique_panel'),
                ),
                migrations.AddConstraint(
                    model_name='cell',
                    constraint=models.UniqueConstraint(fields=('display', 'row', 'col'), name='unique_display_row_col'),
                ),
            ],
        ),
    ]
