# Generated by Django 5.1.4 on 2026-05-30 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_displays', '0006_convert_cell_fk_storage_to_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, help_text='Снимок ФИО — сохраняется даже если пользователь удалён.', max_length=80, verbose_name='имя автора (snapshot)')),
                ('department', models.CharField(blank=True, help_text='Отдел автора на момент записи (monitoring/control/service/admin).', max_length=20, verbose_name='отдел автора')),
                ('text', models.TextField(verbose_name='текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_notes', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='directory_displays.display', verbose_name='экран')),
            ],
            options={
                'verbose_name': 'Заметка об экране',
                'verbose_name_plural': 'Заметки об экране',
                'db_table': 'display_note',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
