# Generated by Django 5.1.4 on 2025-05-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True, verbose_name='Айди сообщения')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработано в')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено в')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='Полный текст сообщения')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_time', models.CharField(max_length=50, verbose_name='Время сигнала')),
                ('slot_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Слот')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус')),
                ('display', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alarms', to='zip.display', to_field='name', verbose_name='Экран')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='mail.gmailmessage', verbose_name='Связанное сообщение')),
            ],
            options={
                'verbose_name': 'сигнал',
                'verbose_name_plural': 'Сигналы',
                'ordering': ['-alarm_time'],
            },
        ),
    ]
