# Generated by Django 5.1.4 on 2026-05-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_legacy_message_template'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='notification',
                    new_name='notificatio_recipie_61ba89_idx',
                    old_name='notificatio_recipie_f683ec_idx',
                ),
            ],
        ),
    ]
