# Generated by Django 5.1.4 on 2026-05-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_departures', '0003_contact_state_import'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterModelOptions(
                    name='departure',
                    options={'ordering': ['id'], 'verbose_name': 'Выезд', 'verbose_name_plural': 'Выезды'},
                ),
                migrations.AlterModelOptions(
                    name='departurehistoryreport',
                    options={'ordering': ['id'], 'verbose_name': 'История выезда (legacy)', 'verbose_name_plural': 'История выездов (legacy)'},
                ),
                migrations.AlterModelOptions(
                    name='departurestatus',
                    options={'ordering': ['order', 'id'], 'verbose_name': 'Статус выезда', 'verbose_name_plural': 'Статусы выездов'},
                ),
                migrations.AlterModelOptions(
                    name='executor',
                    options={'ordering': ['id'], 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
                ),
                migrations.AlterField(
                    model_name='contact',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='departure',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='departure',
                    name='notification',
                    field=models.JSONField(blank=True, null=True, verbose_name='Уведомления'),
                ),
                migrations.AlterField(
                    model_name='departure',
                    name='status_legacy',
                    field=models.CharField(blank=True, db_column='status_legacy', default='', max_length=40, verbose_name='Статус (legacy, удалить после backfill)'),
                ),
                migrations.AlterField(
                    model_name='departure',
                    name='time_created',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания'),
                ),
                migrations.AlterField(
                    model_name='departure',
                    name='time_end',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание выезда'),
                ),
                migrations.AlterField(
                    model_name='departure',
                    name='time_start',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Начало выезда'),
                ),
                migrations.AlterField(
                    model_name='departure',
                    name='time_updated',
                    field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее взаимодействие'),
                ),
                migrations.AlterField(
                    model_name='departurehistoryreport',
                    name='description',
                    field=models.TextField(blank=True, null=True, verbose_name='Описание'),
                ),
                migrations.AlterField(
                    model_name='departurehistoryreport',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='departurestatus',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='executor',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
        ),
    ]
